version: "3.8"
services:
      databaseimg:
        build: ./database
        environment:
        MYSQL_ROOT_PASSWORD: "1234"
        MYSQL_DATABASE: "studentapp"
        MYSQL_USER: "sayyam"
        MYSQL_PASSWORD: "1234"
        ports:
         - 3306:3306
        network_mode: bridge
      frontend:
        build: /root/Docker_studentapp/Frontend
        container_name : frontend
        ports : 
          - 80:80
        network_mode: bridge
      backend:
        build: /root/Docker_studentapp/Backend
        container_name : backend
        ports : 
          - 8080:8080
        depends_on :
          - frontend
        network_mode: bridge
    
